Repository LikeLion-at-DGU/2025_fall_festival_front, pull requests merged in 2025-09, with the labels that each got.

#33 Fix Toilet.png import path 배포 오류 해결
  src/components/ToiletCard/ToiletCard.jsx
Labels: bug

#41 ✨ (#36)Feat:바텀시트 및 카드 디자인 수정
  src/components/Layout.jsx
  src/components/MapComponents/BeerCard.jsx
  src/components/MapComponents/BoothCard.jsx
  src/components/MapComponents/ConvenienceCard.jsx
  src/components/MapComponents/FilterButton.jsx
  src/components/MapComponents/LocationPin.jsx
  src/components/MapComponents/ToiletCard.jsx
  src/pages/Map/Map.jsx
Labels: feat

#39 💄 (#34) Feat: 메인페이지 UI 구현
  src/assets/images/banners/festival-banner.png
  src/assets/images/banners/stage1-ex.png
  src/assets/images/icons/main-icons/notification.svg
  src/assets/images/icons/main-icons/stage.svg
  src/components/HomepageComponents/Banner.jsx
  src/components/HomepageComponents/BoothRank.jsx
  src/components/HomepageComponents/Event.jsx
  src/components/HomepageComponents/Notification.jsx
  src/components/HomepageComponents/Stage.jsx
  src/pages/Home/Home.jsx
  tailwind.config.js
Labels: feat

#100 ✨ (#34) Feat: 메인페이지 API 연동
  index.html
  src/apis/mainpage.js
  src/assets/images/banners/changmo.png
  src/assets/images/banners/festival-banner2.png
  src/assets/images/banners/festival-banner3.png
  src/assets/images/banners/festival-banner4.png
  src/assets/images/banners/fromis9.png
  src/assets/images/banners/ftisland.png
  src/assets/images/banners/haha.png
  src/assets/images/banners/illit.png
  src/assets/images/banners/sole.png
  src/assets/images/icons/logo/favicon.svg
  src/components/AdminComponents/Stuco/PhotoUpload 2.jsx
  src/components/Header/BoardDetailHeader.jsx
  src/components/Header/MapDetailHeader.jsx
  src/components/HomepageComponents/Banner.jsx
  src/components/HomepageComponents/BoothRank.jsx
  src/components/HomepageComponents/Event.jsx
  src/components/HomepageComponents/Notification.jsx
  src/components/HomepageComponents/Stage.jsx
  src/components/MapComponents/BoothCard.jsx
  src/components/MapComponents/BoothCardComponents/Badge 2.jsx
  src/components/MapComponents/NotBoothCard.jsx
  src/hooks/useBoothLikes.js
  src/pages/Home/Home.jsx
  src/pages/Map/DetailSections/BoothDetail 2.jsx
  src/pages/Map/DetailSections/BoothDetail.jsx
  src/pages/Map/DetailSections/DrinkDetail 2.jsx
  src/pages/Map/DetailSections/FoodTruckDetail 2.jsx
  src/pages/Map/DetailSections/MenuSection 2.jsx
  src/pages/Map/DetailSections/NearbyBoothSection 2.jsx
  src/pages/Map/DetailSections/Section 2.jsx
  src/pages/Map/DetailSections/ToiletDetail 2.jsx
  src/utils/dateUtils.js
  tailwind.config.js
Labels: feat, fix, API

#108 ✨ (#25) Feat: 개발자페이지 ui 구현
  src/assets/images/banners/profile-backgroud.png
  src/assets/images/icons/logo/likelion-filter.png
  src/assets/images/profile/baekjiyeon.png
  src/assets/images/profile/choiseonwoo.png
  src/assets/images/profile/hayeonhee.png
  src/assets/images/profile/jangsunwoo.png
  src/assets/images/profile/jominjeong.png
  src/assets/images/profile/kimhongyeon.png
  src/assets/images/profile/kimyumi.png
  src/assets/images/profile/kwakdoyoon.png
  src/assets/images/profile/kwonsuhyeon.png
  src/assets/images/profile/leeboyeon.png
  src/assets/images/profile/leehyeonwook.png
  src/assets/images/profile/leeyeonwoo.png
  src/assets/images/profile/namsoi.png
  src/assets/images/profile/ohsein.png
  src/assets/images/profile/parkjinhee.png
  src/assets/images/profile/parkjunhong.png
  src/assets/images/profile/parkseongjun.png
  src/assets/images/profile/parkseoyeon.png
  src/assets/images/profile/parksumin.png
  src/assets/images/profile/parksuyeon.png
  src/assets/images/profile/parkwon.png
  src/assets/images/profile/shinyumin.png
  src/assets/images/profile/sonyoungchae.png
  src/assets/images/profile/yoonheewon.png
  src/components/DevelopersComponents/PersonCard.jsx
  src/data/developers.js
  src/pages/Developers/Developers.jsx
Labels: feat

#123 ✨ Feat:게임 페이지(#120)
  pnpm-lock.yaml
  src/components/GameComponents/ActionButton.jsx
  src/components/GameComponents/GameHeader.jsx
  src/components/GameComponents/ProgressBar.jsx
  src/components/GameComponents/StatusMessage.jsx
  src/components/GameComponents/WordCard.jsx
  src/components/GameComponents/WordGrid.jsx
  src/components/Layout.jsx
  src/pages/Event/Event.jsx
  src/pages/Event/EventNew.jsx
  src/pages/Event/GameCountdown.jsx
  src/pages/Event/GameIntro.jsx
  src/pages/Event/GameIntroPage.jsx
  src/pages/Event/GamePlay.jsx
  src/utils/gameData.js
  src/utils/gameDataNew.js
Labels: feat

#159 🐛 (#158) Bug: 메인페이지 QA 수정사항 반영
  src/components/HomepageComponents/Banner.jsx
  src/components/HomepageComponents/Event.jsx
  src/components/HomepageComponents/Notification.jsx
  src/components/MapComponents/BoothCard.jsx
  src/pages/Board/Board.jsx
Labels: bug

#172 💄 Fix: 페이지 이동 시 맨 위로 이동되도록 수정
  src/components/ScrollToTop.jsx
  src/routes/Router.jsx
Labels: fix

#255 ✨ (#184)feat:PullList translate
  src/App.jsx
  src/components/MapComponents/PullList.jsx
  src/context/TranslationContext.jsx
  src/hooks/useTranslation.js
  src/styles/tailwind.css
  src/utils/axiosInstance.js
  src/utils/translationApi.js
Labels: feat

#268 Feat/Boothdetail,boothcard translate
  src/components/MapComponents/BoothCard.jsx
  src/locales/en.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/zh-CN.json
  src/pages/Map/DetailSections/BoothDetail.jsx
  src/pages/Map/DetailSections/MenuSection.jsx
Labels: feat

#273 🔥 Feat: pulllist 번역시 불필요한 console제거
  src/components/MapComponents/PullList.jsx
Labels: feat

#299 Feat: Developers role,major translate
  src/components/DevelopersComponents/PersonCard.jsx
  src/pages/Developers/Developers.jsx
  src/utils/translationApi.js
Labels: feat
